name: Compile & release listfile
on:
  push:
    paths:
      -  parts/**
jobs:
  compile-release-listfile:
    name: Build release listfile
    runs-on: ubuntu-latest
    steps:
    - name: Set tag name
      run: echo "NOW=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.NOW }}',
              sha: context.sha
          })
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Compile community listfile with ListfileTool
      run: mkdir $PWD/tmp && dotnet run --project $PWD/tools/ListfileTool --configuration Release -- compile $PWD/parts $PWD/tmp
    - name: Compile verified listfile with ListfileTool
      run: dotnet run --project $PWD/tools/ListfileTool --configuration Release -- compileVerified $PWD/parts $PWD/tmp
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v0.1.13
      with:
        name: Full listfile v${{ env.NOW }}
        draft: false
        prerelease: false
        tag_name: ${{ env.NOW }}    
        files: |
            tmp/community-listfile.csv
            tmp/community-listfile-withcapitals.csv
            tmp/verified-listfile.csv
            tmp/verified-listfile-withcapitals.csv
